{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\ntest_alluredemo.py:19: Exception"}, "start": 1587610715661, "stop": 1587610715661, "uuid": "74d9380c-483c-4627-9efb-ecea6ff827b6", "historyId": "fb799eecaee64eb20ac70a0047ddd7ff", "testCaseId": "54327feac6bee8ccd45a88d670bf2886", "fullName": "test_alluredemo#test_broken", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "mac-lee.local"}, {"name": "thread", "value": "10212-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}